// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggapbfdzlsezrdvzzxlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnYXBiZmR6bHNlenJkdnp6eGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODM1MjAsImV4cCI6MjA2MDM1OTUyMH0.Z58qYk_sa0UG5xPtSqosspblGRsci3mNt0xXjZ6__tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);